<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYcmBkVP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYcmBkVP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYcmBkVP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYcmBkVP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYcmBkVP\App_KernelDevDebugContainer([
    'container.build_hash' => 'YcmBkVP',
    'container.build_id' => '87a0de00',
    'container.build_time' => 1657537844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYcmBkVP');
