<?php

namespace Container8T9uHyi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFollowUpdatedListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\FollowUpdatedListener' shared autowired service.
     *
     * @return \App\EventListener\FollowUpdatedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/EventSubscriber/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/EventListener/FollowUpdatedListener.php';

        return $container->privates['App\\EventListener\\FollowUpdatedListener'] = new \App\EventListener\FollowUpdatedListener(($container->privates['App\\Service\\FollowReader'] ?? $container->load('getFollowReaderService')), ($container->privates['App\\Service\\UserWriter'] ?? $container->load('getUserWriterService')));
    }
}
